### ISSUE TITLE
Do I need to change anything when running the reproducable demo?

### ISSUE THREAD

**Issue by klion26** [jcaesar/flink-rocksdb-file-leak#1]
Hi @jcfj I'm currently following the issue [FLINK-13808](https://issues.apache.org/jira/browse/FLINK-13808).
 when run the command in the readme, I just received the following exception, do I need to change anything ? thanks
```
taskmanager1_1  | 2019-08-29 11:58:23,187 INFO  org.apache.flink.runtime.taskexecutor.TaskManagerRunner       - Actor system started at akka.tcp://flink-metrics@172.19.0.9:38847
zookeeper3_1    | 2019-08-29 11:58:37,830 [myid:3] - ERROR [LearnerHandler-/172.19.0.2:38638:LearnerHandler@648] - Unexpected exception causing shutdown while sock still open
zookeeper3_1    | java.net.SocketTimeoutException: Read timed out
zookeeper3_1    | 	at java.net.SocketInputStream.socketRead0(Native Method)
zookeeper3_1    | 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
zookeeper3_1    | 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
zookeeper3_1    | 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
zookeeper3_1    | 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
zookeeper3_1    | 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
zookeeper3_1    | 	at java.io.DataInputStream.readInt(DataInputStream.java:387)
zookeeper3_1    | 	at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:63)
zookeeper3_1    | 	at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:85)
zookeeper3_1    | 	at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:99)
zookeeper3_1    | 	at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:559)
zookeeper3_1    | 2019-08-29 11:58:37,830 [myid:3] - ERROR [LearnerHandler-/172.19.0.3:33276:LearnerHandler@648] - Unexpected exception causing shutdown while sock still open
zookeeper3_1    | java.net.SocketTimeoutException: Read timed out
zookeeper3_1    | 	at java.net.SocketInputStream.socketRead0(Native Method)
zookeeper3_1    | 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
zookeeper3_1    | 	at java.net.SocketInputStream.read(SocketInputStream.java:171)
zookeeper3_1    | 	at java.net.SocketInputStream.read(SocketInputStream.java:141)
zookeeper3_1    | 	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
zookeeper3_1    | 	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
zookeeper3_1    | 	at java.io.DataInputStream.readInt(DataInputStream.java:387)
zookeeper3_1    | 	at org.apache.jute.BinaryInputArchive.readInt(BinaryInputArchive.java:63)
zookeeper3_1    | 	at org.apache.zookeeper.server.quorum.QuorumPacket.deserialize(QuorumPacket.java:85)
zookeeper3_1    | 	at org.apache.jute.BinaryInputArchive.readRecord(BinaryInputArchive.java:99)
zookeeper3_1    | 	at org.apache.zookeeper.server.quorum.LearnerHandler.run(LearnerHandler.java:559)
zookeeper3_1    | 2019-08-29 11:58:38,085 [myid:3] - WARN  [LearnerHandler-/172.19.0.3:33276:LearnerHandler@661] - ******* GOODBYE /172.19.0.3:33276 ********
zookeeper3_1    | 2019-08-29 11:58:38,085 [myid:3] - WARN  [LearnerHandler-/172.19.0.2:38638:LearnerHandler@661] - ******* GOODBYE /172.19.0.2:38638 ********
zookeeper2_1    | 2019-08-29 11:58:37,922 [myid:2] - WARN  [QuorumPeer[myid=2]/0.0.0.0:2181:Follower@90] - Exception when following the leader
zookeeper2_1    | java.net.SocketTimeoutException: Read timed out
```

**Comment by jcfj** [comment]
Thank you for looking into it.

I'm not sure where that problem comes from, but it seems like the zookeeper containers can't communicate. Might be either an old docker/docker-compose version or one of those [weird docker networking bugs](https://github.com/moby/moby/issues/18169)… I suggest we sidestep the problem and use some common environment.

I've tried the following on an `ami-003371bfa26192744` (Ubuntu bionic, login name: `ubuntu`, disk increased to 50GB) on a `m5.2xlarge` from AWS:

```
sudo apt update
sudo apt install -y docker-compose parallel
echo "will cite" | parallel --citation
sudo usermod -aG docker ubuntu
newgrp docker
git clone https://github.com/jcaesar/flink-rocksdb-file-leak
cd flink-rocksdb-file-leak/
docker-compose kill; docker-compose rm -vfs; docker-compose up --build --abort-on-container-exit
```
and was promptly able to reproduce the behavior.

In case you don't use AWS (iirc getting an account was relatively annoying), I can see whether I can give you access to an instance. (Alternatively, I also have a DigitalOcean account, if you'd like to use that as a common environment.)

**Comment by klion26** [comment]
@jcfj thanks for your reply and sharing my instance to reproduce the issue.
Currently, I can reproduce your problem in another machine.

I prepared a patch for tracking this problem, Could you please tell me how to run the custom Flink within docker mode? thanks.

**Comment by jcaesar** [comment]
You could modify the [Dockerfile](https://github.com/docker-flink/docker-flink/blob/master/1.8/scala_2.11-debian/Dockerfile#L65) that the official Flink image uses to not download the release tar but copy it from your machine. Then, I think it should be enough to build that with 
```bash
docker build -t flink:1.8.1-scala_2.11
```

But I think I have a Dockerfile on my work machine that does this more conveniently, I'll send it on monday.

**Comment by jcfj** [comment]
I've updated the repo a bit, the following works for me:

```
export FLINK_DOCKERFILE=flink-sourcebuilt.Dockerfile
rm -rf flink/flink-src; mkdir flink/flink-src
cd flink/flink-src
http -d http://ftp.kddilabs.jp/infosystems/apache/flink/flink-1.8.1/flink-1.8.1-bin-scala_2.11.tgz
tar --strip-components=1 -xvf flink-1.8.1-bin-scala_2.11.tgz
```

I hope that does the trick.

**Comment by jcfj** [comment]
Actually, if you'd like to share the patch, I'd also test it on the cluster here.

**Comment by klion26** [comment]
@jcfj thanks for your reply. I'll push a branch to GitHub and update it here late.

**Comment by klion26** [comment]
@jcfj I've pushed the [branch](https://github.com/klion26/flink/tree/add_log_for_tracking) to Github, this branch is based on release-1.8, added some log for tracking this problem.

**Comment by klion26** [comment]
@jcfj AFAIK, this problem may be caused by IO problem, could you please check the io state when  there are files leaded, (`iostate` of `sar`)

The *leaked* files were still uploading, so they would not be deleted.

**Comment by klion26** [comment]
I run on a new machine(which has a better disk performance) with the updated patch, there may be some files *leaked* for a moment, and a few seconds later, the *leaked files* will be deleted.

**Comment by klion26** [comment]
@jcfj What do you think about the previous conclusion I gave(IO is the culprit). If that ok to you, then I'll update the conclusion to the jira side, and will propose some optimization to improve such scenario

**Comment by jcfj** [comment]
I was busy and haven't gotten around to testing it yet. (Somehow, frocksdbjni suddenly want's jemalloc 2… not sure what I'm doing wrong.) I think it's a bit unlikely, since I've seen checkpoints consistently remain for a long time, and in high numbers.

**Comment by klion26** [comment]
@jcfj I'm not sure what the jemalloc problem you mentioned here, and please let me know If need I to check something.
If the previous conclusion is correct, there may be some files leaked for a long time, the time depends on the io state, the *leaked file* is on the tm side, thery are still uploading to the hdfs(because the snapshot of tm side did not know that the checkpoint is failed in current flink version)

The (not full) step is as follow:
1. JM trigger checkpoint
2. TM start snapshot
3. TM uploading sst files to HDFS
4. uploading successfully, and delete the directory if needed
5. tell JM that the snapshot is successful

Currently, from what I observed is that the step 3 took too long time,  so the files would not be deleted(we can see the files leaked in the local directory).

And please let me know after you tested with the updated patch, thanks.

**Comment by jcfj** [comment]
Okay, got it to run.

In the case with no local recovery, it is as you say, I see a `2019-09-05 15:33:23,985 INFO  org.apache.flink.contrib.streaming.state.RocksDBStateUploader  - Create one future for 31 thread Thread[pool-180-thread-2,5,Flink Task Threads] path file:/mnt/nvme0/2/flink-io-92c4e144-46ae-419d-a75d-bbc4e3a8e2ef/job_e6b6117dba0dc4afee1f5fb0135e95f3_op_KeyedProcessOperator_d839f9d86e16822ece60fa5d60238c55__17_120__uuid_9b3d8868-2c84-4587-873a-a826d23a728d/chk-31/000225.sst directory SnapshotDirectory{directory=/mnt/nvme0/2/flink-io-92c4e144-46ae-419d-a75d-bbc4e3a8e2ef/job_e6b6117dba0dc4afee1f5fb0135e95f3_op_KeyedProcessOperator_d839f9d86e16822ece60fa5d60238c55__17_120__uuid_9b3d8868-2c84-4587-873a-a826d23a728d/chk-31, state=ONGOING}.
`.
It doesn't really help, btw, that the files will be deleted *eventually* because by then my disks may be full. In this case, I've only waited until 15 checkpoints were accumulated, but I've waited to up to 50 before, with nothing being deleted over the course of 30 minutes.

The case with local recovery is even more interesting. It did print `2019-09-05 15:11:18,267 TRACE org.apache.flink.contrib.streaming.state.snapshot.RocksIncrementalSnapshotStrategy  - Running cleanup for local RocksDB backup directory SnapshotDirectory{directory=file:/mnt/nvme0/1/localState/aid_f64afafc945e5037b3d1bf4d64a8a4b3/jid_7bd396d424462ae606bb6050bf808684/vtx_7cb5514633b416127fbd718e0831a548_sti_51/chk_29/rocks_db, state=COMPLETED}.` and the file was still there.

I've thrown the files into https://github.com/jcaesar/flink-rocksdb-file-leak/tree/log

**Comment by klion26** [comment]
@jcfj thank you for the quick update
- Sorry for not share how to use the patch, my bad:(. the log I added is to locate where the problem stuck, previously I did the following steps:
  - when I observed there are some files leaked, then I will check the checkpoint for the backend (use the directory (`job_e6b6117dba0dc4afee1f5fb0135e95f3_op_KeyedProcessOperator_d839f9d86e16822ece60fa5d60238c55__17_120__uuid_9b3d8868-2c84-4587-873a-a826d23a728d`)  to search  in the tm log), and find the last log it did not shown up (but it should show), to find out where the snapshot stuck.
   - previously as I tested, I found that the snapshot will be stuck in the uploading procedure, because there will be log such as `Before createUploadFutures for {} thread {} directory {}.` but the `Create one future for {} thread {} path {} directory {}.` did not show up, so I gave the conclusion that the io is the culprit.
 - as the log you gave showed that there are some log(upload sst files for checkpoint 31) `2019-09-05 15:34:41,711 INFO  org.apache.flink.contrib.streaming.state.RocksDBStateUploader  - Create one future for 31 thread Thread[pool-193-thread-2,5,Flink Task Threads] path file:/mnt/nvme0/0/flink-io-b9d49b4a-a8cc-4b5e-9bcc-fcdb0e0396c3/job_e6b6117dba0dc4afee1f5fb0135e95f3_op_KeyedProcessOperator_d839f9d86e16822ece60fa5d60238c55__62_120__uuid_e6ff2343-6f30-4cc9-beb7-24ab90671b77/chk-31/000140.sst directory SnapshotDirectory{directory=/mnt/nvme0/0/flink-io-b9d49b4a-a8cc-4b5e-9bcc-fcdb0e0396c3/job_e6b6117dba0dc4afee1f5fb0135e95f3_op_KeyedProcessOperator_d839f9d86e16822ece60fa5d60238c55__62_120__uuid_e6ff2343-6f30-4cc9-beb7-24ab90671b77/chk-31, state=ONGOING}` shown after the checkpoint 45 start.
`2019-09-05 15:34:40,436 INFO  org.apache.flink.contrib.streaming.state.snapshot.RocksIncrementalSnapshotStrategy  - start callInternal for 45`, this means uploading sst files for checkpoint 33 took too long time to complete
- could you please share the io state? (the output of `sar -d` when running the flink job), thanks 
- when enabling local recovery, the directory will be deleted after completed the next checkpoint (because it may be used for recovery, if there are newer checkpoint complete, then this local checkpoint can be deleted, please check the code here[1]) if there are no complete checkpoint, the directory would not be deleted for now (this can be optimized)


[1] https://github.com/apache/flink/blob/e0759c3776e7292e4a4937c6fb76d31ce7bf702d/flink-runtime/src/main/java/org/apache/flink/runtime/state/TaskLocalStateStoreImpl.java#L216

**Comment by jcfj** [comment]
> when enabling local recovery, the directory will be deleted after completed the next checkpoint (because it may be used for recovery, if there are newer checkpoint complete, then this local checkpoint can be deleted, please check the code here[1]) if there are no complete checkpoint, the directory would not be deleted for now (this can be optimized)

Just so I don't misunderstand you: incomplete checkpoints will never be reused, the code to clean them up properly is just not implemented?

> could you please share the io state? (the output of sar -d when running the flink job), thanks

I've thrown one for one HDFS node and one for one Taskexecutor node into the [repo](https://github.com/jcaesar/flink-rocksdb-file-leak/tree/be052c8bc320a22b4ba0318ad59f774bb33285af). I've stopped the job at 16:56:34 to also show what idle would look like. The Taskexecutor has two NVMe SSDs, Flink uses them through LVM.

I'm a bit unsure what you want to learn from these. The IO on the Taskexecutors should go down rather low once the workload is finished (I can wait for that and show you if you want), but the workload on the HDFS nodes will inevitably be high forever, since the failing large checkpoints are retried forever.

**Comment by klion26** [comment]
@jcfj thanks for your quick reply.
> Just so I don't misunderstand you: incomplete checkpoints will never be used for recovery, the code to clean them up properly is just not implemented?
Yes, currently, It is not implemented yet.


> I've thrown one for one HDFS node and one for one Taskexecutor node into the [repo](https://github.com/jcaesar/flink-rocksdb-file-leak/tree/be052c8bc320a22b4ba0318ad59f774bb33285af). I've stopped the job at 16:56:34 to also show what idle would look like. The Taskexecutor has two NVMe SSDs, Flink uses them through a raid0 style LVM.
> 
> I'm a bit unsure what you want to learn from these. The ([Edit:] **write**) IO on the Taskexecutors should go down rather low once the workload is finished (I can wait for that and show you if you want), but the workload on the HDFS nodes will inevitably be high forever, since the failing large checkpoints are retried forever.
From I analysis, the issue was caused by IO problem(upload is too slow because by the IO pressure) and some unimplemented feature(a. can not cancel failed snapshot in TM, can not delete local state -- enabled local recovery, if no checkpoint complete) in Flink. I just want to double-check the problem was caused by IO pressure.
As the `sar log` you gave showed that when job running, the IO is truly high, I think the two things matched(the checkpoint can not complete because of high io pressure), what do you think about this?

**Comment by jcfj** [comment]
I guess so. (Although I think the bottleneck is the network, not the disks. I've only got 30Gbit/s upstream to my HDFS.)

I take it all the checkpoints get the same priority for upload, meaning that as more and more checkpoints are tried, they get slower and slower.

**Comment by klion26** [comment]
@jcfj yes, currently, all checkpoints get the same priority for upload.
I'll conclude this issue on the jira side, thanks for all the help to analysis this issue :)
